# https://projecteuler.net/problem=101
# Given a sequence, we model with polynomials of order n based on the first n+1 terms
# e.g. a quadratic based on the first 3 terms
# If this was a good model, it would be accurate past n+1, but it usually isn't
# We collect the modeled n+2 terms when they're wrong and add them all up
# in this case for the sequence generated by u(n) = 1-n+n**2-n**3+n**4-n**5+n**6-n**7+n**8-n**9+n**10

def interp(points, x):
    n = len(points)
    num = [1]*n
    den=[1]*n
    ans = 0
    for i in range(n):
        for j in range(n):
            if i != j:
                num[i] *= (x-j)
                den[i] *= (i-j)
    for i in range(n):
        ans += num[i]*points[i]/den[i]
    return(ans)

def u(n):
    return(1-n+n**2-n**3+n**4-n**5+n**6-n**7+n**8-n**9+n**10)

u_terms = [u(n) for n in range(1,15)]

def FIT(o:int, u_terms:list): #First Incorrect Terms
    i=1
    t = interp(u_terms[:o],i)
    while i < len(u_terms) and t == u_terms[i]:
        i += 1
        t = interp(u_terms[:o], i)
    if i < len(u_terms):
        return(t)
    else:
        return 0
total = 0
for i in range(1,15):
    f = FIT(i,u_terms)
    #print(f)
    total += f
print(int(total))
